### ISSUE TITLE
Trenger funksjonalitet for å hente ut e-post adresse fra et issue

### ISSUE THREAD

**Issue by tommyalmendingen** [Altinn/apps-backlog#74]
I forbindelse med at vi skal ta i bruk GitHub som erstatning for HPSM trenger vi hjelp til å lage en GitHub Acton som henter ut en e-post adresse fra et issue. 

## Beskrivelse
Når bruker sender inn en sak fra altinndigital.no opprettes automatisk et nytt issue i et gitt repository. Til testing har vi brukt følgende repository og det ligger nå noen åpne saker her: 
https://github.com/tommyalmendingen/support-test/issues

![image](https://user-images.githubusercontent.com/45939254/178955507-7df17fca-be33-459d-8da2-3978ddaaa14a.png)

Når nytt issue opprettes trigges en GitHub Action som må gjøre følgende:
1. Legger issue til et gitt prosjekt
2. Henter ut e-post adresse som ligger registrert i Issue
3. Sender ut e-post til denne adressen med kvittering/saksnummer, f.eks. "Vi har mottatt din sak

Jeg tenker at 1. 2. og 3. kan være forskjellige "step" i en action fil eller flere Actions om det er bedre. Og at e-post adressen hentes ut som et parameter fra 2. som sendes videre til 3. Både punkt 1. og 3. har jeg fått til, men det er altså det å hente e-post adressen fra issue som gjestår. Hvordan dette implementeres blir opp til dere, det er mulig å bruke skriptspråk som JavaScript, Bash, PowerShell, etc. eller programmeringsspråk som Java, C# osv.

Videre kan dette kanskje se ca. slik ut helt overordnet:

```
name: Legg til nye issues til project og send ut e-post til innsender

on:
  issues:
    types:
      - opened

steps:
  - name: Legg til i prosjekt
    ....
  - name: Hent e-post adresse
    ...
  - name: Send ut e-post
    ...
```

Greie introsider til GitHub Actions:
https://www.freecodecamp.org/news/build-your-first-javascript-github-action/
https://github.blog/2022-02-10-using-reusable-workflows-github-actions/

Dokumentasjon GitHub Actions:
https://docs.github.com/en/actions

Action som legger til i prosjekt og kan gjenbrukes i steg 1.:
https://github.com/tommyalmendingen/support-test/blob/main/.github/workflows/add-to-project.yml

Action som sender ut e-post og som kan gjenbrukes i steg 3.:
https://github.com/tommyalmendingen/actions-test/blob/main/.github/workflows/sendmail.yml
